apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - harbor-externalsecret.yaml
  - harbor-oauth-externalsecret.yaml
  - harbor-pvc.yaml
  - helmrelease.yaml
  - virtualservice.yaml
