apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-cluster-dashboard
  namespace: emqx
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`emqx.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: emqx-cluster-dashboard
          namespace: emqx
          port: 18083
      middlewares:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
