---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hortusfox-config
  namespace: hortusfox
data:
  APP_TIMEZONE: "${timezone}"
  # HAProxy service hostname created by the Percona PXC operator
  DB_HOST: "hortusfox-mysql-haproxy"
  DB_PORT: "3306"
  # The 'hortusfox' database and user are created by the database bootstrap Job.
  DB_DATABASE: "hortusfox"
  DB_USERNAME: "hortusfox"
  DB_CHARSET: "utf8mb4"
