apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clawdbot
  namespace: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`clawdbot.${domain_name}`) && PathPrefix(`/`)
      middlewares:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
      services:
        - kind: Service
          name: clawdbot
          namespace: openclaw
          port: 18789
  tls: {}
