apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./openclaw-helmrelease.yaml
  - ./openclaw-externalsecret.yaml
  - ./openclaw-config-pvc.yaml
  - ./openclaw-documents-pvc.yaml