apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nixos-build-helmrelease.yaml
  - ./nixos-build-nix-pvc.yaml
  - ./nixos-build-ssh-keys-externalsecret.yaml
  - ./nixos-build-cache-keys-externalsecret.yaml
  - ./virtualservice.yaml
