apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./istio-gateway.yaml
  - ./istio-ingress-certificate.yaml
  - ./istio-authentik-authorizationpolicy.yaml
  - ./istiod-servicemonitor.yaml
  - ./istio-ingressgateway-podmonitor.yaml
  - ./istio-vs.yaml