apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`capacitor.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: capacitor
          namespace: monitoring
          port: 9000
  tls: {}
