apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate
  namespace: frigate
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`frigate.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: frigate-main
          namespace: frigate
          port: 5000
      middlewares:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
