apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: homeassistant
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`hass.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: home-assistant-main
          namespace: homeassistant
          port: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zwavejsui
  namespace: homeassistant
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`zwavejsui.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: home-assistant-zwavejsui
          namespace: homeassistant
          port: 8091
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`zigbee2mqtt.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: home-assistant-zigbee2mqtt
          namespace: homeassistant
          port: 8080
