apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./zigbeeemqx-externalsecret.yaml
    - ./helmrelease.yaml
    - ./ingressroute.yaml
    - ./homeassistant-config-pvc.yaml
    - ./homeassistant-cache-pvc.yaml
    - ./zigbee2mqtt-config-pvc.yaml
    - ./zwave-js-ui-pvc.yaml
