apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-s3
  namespace: rustfs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`s3.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: rustfs-s3
          namespace: rustfs
          port: 9000
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-console
  namespace: rustfs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rustfs.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: rustfs-console
          namespace: rustfs
          port: 9001
  tls: {}
