apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: prowlarr
          namespace: media
          port: 8989
      middlewares:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
  tls: {}
