apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openwebui
  namespace: openwebui
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`openwebui.${domain_name}`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: open-webui
      namespace: openwebui
      port: 8080
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
