---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${domain_name}
  namespace: traefik
spec:
  secretName: ${domain_name}
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.${domain_name}"
