apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost-callbacks
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/outpost.goauthentik.io/`)
      priority: 1000
      services:
        - kind: Service
          name: ak-outpost-proxy-outpost
          namespace: authentik
          port: 9000
  tls: {}
