---
ingress:
  - hostname: "*.prizrak.me"
    originRequest:
      http2Origin: true
      httpHostHeader: ""
      matchSNItoHost: true
      noTLSVerify: true
      originServerName: ""
    service: "https://192.168.88.7"

warp-routing:
  enabled: false
