---
originRequest: {}

ingress:
  - hostname: "${domain_name}"
    service: &svc https://istio-ingressgateway.istio-system.svc.cluster.local
  - hostname: "*.${domain_name}"
    service: *svc
  - service: http_status:404
