apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openbooks
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`openbooks.${domain_name}`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: openbooks
          namespace: media
          port: 8080
      middlewares:
        - name: ak-outpost-proxy-outpost
          namespace: authentik
  tls: {}
